"""Generate the paper's tables, plots and numeric macros from measured results."""

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import f1_score, precision_recall_curve

from extended_experiments import CONFIGS, save_json
from prepare_labels import confidence_gate


def write_tex(path, body):
    path.parent.mkdir(parents=True, exist_ok=True)
    header = f"% Generated by src/build_artifacts.py; source: {path.parent.parent.as_posix()}/*.json\n"
    path.write_text(header + body + "\n", encoding="utf-8")


def score_cell(metric):
    return f"${metric['mean']:.3f}\\pm{metric['sample_std']:.3f}$"


def table(caption, label, columns, headings, rows):
    return "\n".join([
        "\\begin{table}[t]", "\\centering", "\\footnotesize",
        "\\caption{" + caption + "}", "\\label{" + label + "}",
        "\\setlength{\\tabcolsep}{4pt}", "\\begin{tabular}{" + columns + "}",
        "\\toprule", " & ".join(headings) + r" \\", "\\midrule",
        *[" & ".join(row) + r" \\" for row in rows],
        "\\bottomrule", "\\end{tabular}", "\\end{table}"])


def paired_bootstrap(name_a, name_b, seeds, predictions, runs, groups, repeats=1000):
    """Resample duplicate-text groups, pairing both models on each replicate."""
    a = [np.load(predictions / f"{name_a}-{seed}.npz") for seed in seeds]
    b = [np.load(predictions / f"{name_b}-{seed}.npz") for seed in seeds]
    truth = a[0]["truth"]
    for p in a + b:
        np.testing.assert_array_equal(p["ids"], a[0]["ids"])
        np.testing.assert_array_equal(p["truth"], truth)
    pa = [p["probability"] >= runs[(name_a, seed)]["threshold"] for p, seed in zip(a, seeds)]
    pb = [p["probability"] >= runs[(name_b, seed)]["threshold"] for p, seed in zip(b, seeds)]
    buckets = [np.flatnonzero(groups == group) for group in np.unique(groups)]
    rng = np.random.default_rng(2026)
    deltas = []
    for _ in range(repeats):
        ids = np.concatenate([buckets[i] for i in rng.integers(len(buckets), size=len(buckets))])
        delta = np.mean([f1_score(truth[ids], x[ids], average="macro", labels=[0, 1], zero_division=0) -
                         f1_score(truth[ids], y[ids], average="macro", labels=[0, 1], zero_division=0)
                         for x, y in zip(pa, pb)])
        deltas.append(delta)
    observed = np.mean([f1_score(truth, x, average="macro", labels=[0, 1], zero_division=0) -
                        f1_score(truth, y, average="macro", labels=[0, 1], zero_division=0) for x, y in zip(pa, pb)])
    return {"model_a": name_a, "model_b": name_b, "mean_delta": float(observed),
            "ci95": np.quantile(deltas, [.025, .975]).tolist(), "replicates": repeats,
            "group_count": len(buckets), "seed": 2026,
            "scope": "conditional on generated targets and the fixed test split"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", default="results/revision-v2")
    parser.add_argument("--labels", required=True)
    parser.add_argument("--predictions", default="work/experiment-cache/revision-v2/predictions")
    parser.add_argument("--label-manifest", required=True)
    args = parser.parse_args()
    root = Path(args.results)
    summary = json.loads((root / "summary.json").read_text())
    baselines = json.loads((root / "baselines.json").read_text())
    manifest = json.loads((root / "manifest.json").read_text())
    scaling = json.loads((root / "scaling.json").read_text())
    teacher_timing = json.loads((root / "teacher_timing.json").read_text())
    if set(summary) != {c.name for c in CONFIGS}:
        raise ValueError("The full prespecified model suite has not finished")
    if any(v["seeds"] != [42, 43, 44] for v in summary.values()):
        raise ValueError("Paper requires the three planned initialization seeds")
    df = pd.read_csv(args.labels, dtype={"tweet_id": str})
    df.clean_text = df.clean_text.fillna("")
    scores = np.load(Path(args.labels).parent / "teacher_scores.npz")["scores"]
    lm = json.loads(Path(args.label_manifest).read_text())
    sensitivity = []
    for threshold in [.50, .60, .70, .75, .80, .85, .90]:
        accepted, _, _, _ = confidence_gate(scores, df.eligible, min_confidence=threshold)
        sensitivity.append({"threshold": threshold, "accepted": int(accepted.sum()),
                            "valid": int((accepted & (df.target == 0)).sum()),
                            "positive": int((accepted & (df.target == 1)).sum()),
                            "coverage": float(accepted.sum() / df.eligible.sum())})
    quality = {"teacher": lm, "rows": len(df), "eligible": int(df.eligible.sum()),
               "accepted": int(df.accepted.sum()),
               "three_way_eligible": df.loc[df.eligible, "misinformation_label"].value_counts().to_dict(),
               "three_way_descriptive_eligible": df.loc[df.eligible, "descriptive_label"].value_counts().to_dict(),
               "prompt_binary_agreement": float(df.loc[df.eligible, "prompt_agreement"].mean()),
               "binary_positive_eligible": int(df.loc[df.eligible, "target"].sum()),
               "binary_positive_accepted": int(df.loc[df.accepted, "target"].sum()),
               "confidence_sensitivity": sensitivity}
    save_json(root / "label_audit.json", quality)
    runs = {(c.name, seed): json.loads((root / "runs" / f"{c.name}-{seed}.json").read_text())
            for c in CONFIGS for seed in (42, 43, 44)}
    predictions = Path(args.predictions)
    ids = np.load(predictions / "SAGE-deep-42.npz")["ids"]
    groups = df.clean_text.iloc[ids].str.casefold().to_numpy()
    comparisons = [paired_bootstrap("SAGE-deep", reference, [42, 43, 44], predictions, runs, groups)
                   for reference in ("SAGE-small", "SAGE-filtered", "MLP-control")]
    save_json(root / "paired_comparisons.json", comparisons)
    latex = root / "latex"
    order = [c.name for c in CONFIGS]
    author_rows = [[name, score_cell(summary[name]["author_macro_f1"])]
                   for name in order if name != "SAGE-single-task"]
    write_tex(latex / "author_table.tex", table(
        "Author identification on the revised grouped split. Mean $\\pm$ sample SD over three seeds.",
        "tab:author-v2", "lc", ["Encoder/configuration", "Macro-F1"], author_rows))
    label_rows = [[name, f"{value['label']['macro_f1']:.3f}",
                   f"{value['label']['positive_precision']:.3f}", f"{value['label']['positive_recall']:.3f}"]
                  for name, value in baselines.items()]
    label_rows += [[name, score_cell(summary[name]["label_macro_f1"]),
                    f"{summary[name]['positive_precision']['mean']:.3f}",
                    f"{summary[name]['positive_recall']['mean']:.3f}"] for name in order]
    write_tex(latex / "label_table.tex", table(
        "Binary teacher-label prediction on every eligible test tweet. Precision/recall refer to misleading or invalid; neural F1 is mean $\\pm$ sample SD.",
        "tab:labels-v2", "lccc", ["Model", "Macro-F1", "Prec.", "Recall"], label_rows))
    runtime_rows = []
    for row in scaling:
        if row["fraction"] == 1:
            runtime_rows.append([row["model"], f"{row['parameters']/1000:.1f}",
                                 f"{1000 * row['train_median_seconds']:.0f}",
                                 f"{1000 * row['inference_median_seconds']:.0f}"])
    write_tex(latex / "runtime_table.tex", table(
        "Full-graph CPU cost: parameter counts in thousands and median warm latency in milliseconds (seven repetitions).",
        "tab:runtime", "lrrr", ["Model", "Params (k)", "Train step", "Inference"], runtime_rows))
    label_rows = []
    for name, mask in (("All tweets", np.ones(len(df), dtype=bool)),
                       ("Eligible text", df.eligible.to_numpy()),
                       ("Accepted labels", df.accepted.to_numpy())):
        # Ineligible rows do not have an interpretable teacher class.
        valid = int((mask & df.eligible & (df.target == 0)).sum())
        positive = int((mask & df.eligible & (df.target == 1)).sum())
        label_rows.append([name, f"{int(mask.sum()):,}",
                           "--" if name == "All tweets" else f"{valid:,}",
                           "--" if name == "All tweets" else f"{positive:,}"])
    write_tex(latex / "quality_table.tex", table(
        "Label cascade. Short/link-only texts have no supervised target; accepted rows pass both prompt and confidence checks.",
        "tab:quality", "lrrr", ["Stage", "Tweets", "Valid", "Misleading/invalid"], label_rows))
    macros = {
        "NumTweets": f"{len(df):,}", "NumEligible": f"{df.eligible.sum():,}",
        "NumIneligible": f"{(~df.eligible).sum():,}", "NumAccepted": f"{df.accepted.sum():,}",
        "GateCoverage": f"{100 * df.accepted.sum() / df.eligible.sum():.1f}",
        "PromptAgreement": f"{100 * quality['prompt_binary_agreement']:.1f}",
        "LooseGateCoverage": f"{100 * next(r['coverage'] for r in sensitivity if r['threshold'] == .60):.1f}",
        "StrictGateCoverage": f"{100 * next(r['coverage'] for r in sensitivity if r['threshold'] == .90):.1f}",
        "EligiblePositiveRate": f"{100 * quality['binary_positive_eligible'] / quality['eligible']:.1f}",
        "AcceptedPositiveRate": f"{100 * quality['binary_positive_accepted'] / quality['accepted']:.1f}",
        "NumTrain": f"{manifest['split']['train']['n']:,}",
        "NumValidation": f"{manifest['split']['val']['n']:,}",
        "NumTest": f"{manifest['split']['test']['n']:,}",
        "NumFilteredTrain": f"{manifest['split']['train']['accepted']:,}",
        "NumEdges": f"{manifest['graph']['directed_edges']:,}",
        "NumAccounts": f"{manifest['graph']['accounts']:,}",
        "NumIsolated": f"{manifest['graph']['tweet_nodes_without_retweeter_edges']:,}",
        "TextFOne": f"{baselines['Text-LR']['label']['macro_f1']:.3f}",
        "FilteredTextFOne": f"{baselines['Text-LR-filtered']['label']['macro_f1']:.3f}",
    }
    mapping = {"Small": "SAGE-small", "Filtered": "SAGE-filtered", "Wide": "SAGE-wide",
               "Large": "SAGE-deep", "MLP": "MLP-control", "NoEdges": "SAGE-no-edges",
               "Single": "SAGE-single-task", "TFIDF": "SAGE-TFIDF"}
    for prefix, name in mapping.items():
        macros[prefix + "FOne"] = f"{summary[name]['label_macro_f1']['mean']:.3f}"
        macros[prefix + "AuthorFOne"] = f"{summary[name]['author_macro_f1']['mean']:.3f}"
        macros[prefix + "Parameters"] = f"{summary[name]['parameters']:,}"
    for prefix, reference in (("Small", "SAGE-small"), ("Filtered", "SAGE-filtered"), ("MLP", "MLP-control")):
        comparison = next(c for c in comparisons if c["model_b"] == reference)
        macros[prefix + "Delta"] = "\\ensuremath{" + f"{comparison['mean_delta']:+.4f}" + "}"
        interval = f"[{comparison['ci95'][0]:+.4f}, {comparison['ci95'][1]:+.4f}]"
        macros[prefix + "DeltaCI"] = "\\mbox{\\ensuremath{" + interval + "}}"
    full = {r["model"]: r for r in scaling if r["fraction"] == 1}
    macros["LargeTimeRatio"] = f"{full['SAGE-deep']['train_median_seconds']/full['SAGE-small']['train_median_seconds']:.2f}"
    for row in teacher_timing["rows"]:
        macros["TeacherRate" + {3: "Small", 12: "Medium", 24: "Large"}[row["pair_batch_size"]]] = f"{row['tweets_per_second']:.2f}"
    write_tex(latex / "macros.tex", "\n".join("\\newcommand{\\" + name + "}{" + value + "}" for name, value in macros.items()))
    plot = ["\\begin{figure}[t]", "\\centering", "\\begin{tikzpicture}",
            "\\begin{axis}[width=\\columnwidth,height=5cm,xlabel={Tweet nodes},ylabel={Warm train step (s)},",
            "legend style={font=\\scriptsize,at={(0.02,0.98)},anchor=north west},",
            "tick label style={font=\\scriptsize},label style={font=\\footnotesize},grid=major]"]
    for name in ("SAGE-small", "SAGE-wide", "SAGE-deep", "GAT-small"):
        points = [(r["tweets"], r["train_median_seconds"]) for r in scaling if r["model"] == name]
        plot.append("\\addplot+[mark=*] coordinates {" + " ".join(f"({n},{t:.5f})" for n, t in points) + "};")
        plot.append("\\addlegendentry{" + name + "}")
    plot += ["\\end{axis}", "\\end{tikzpicture}",
             "\\caption{Measured optimizer-step scaling on nested real tweet subgraphs plus their account neighbors. No synthetic tweets are added.}",
             "\\label{fig:scaling}", "\\end{figure}"]
    write_tex(latex / "scaling_plot.tex", "\n".join(plot))
    plot = ["\\begin{figure}[t]", "\\centering", "\\begin{tikzpicture}",
            "\\begin{axis}[width=\\columnwidth,height=4.6cm,xlabel={Recall},ylabel={Precision},",
            "xmin=0,xmax=1,ymin=0,ymax=1,grid=major,",
            "legend style={font=\\scriptsize,at={(0.03,0.03)},anchor=south west},",
            "tick label style={font=\\scriptsize},label style={font=\\footnotesize}]"]
    curves = {}
    for name in ("SAGE-small", "SAGE-deep", "MLP-control"):
        p = np.load(predictions / f"{name}-42.npz")
        precision, recall, _ = precision_recall_curve(p["truth"], p["probability"])
        chosen = np.unique(np.linspace(0, len(recall) - 1, min(100, len(recall))).astype(int))
        points = [(float(recall[i]), float(precision[i])) for i in chosen]
        curves[name] = points
        plot.append("\\addplot+[no marks] coordinates {" + " ".join(f"({r:.4f},{p:.4f})" for r, p in points) + "};")
        plot.append("\\addlegendentry{" + name + "}")
    plot += ["\\end{axis}", "\\end{tikzpicture}",
             "\\caption{Precision--recall curves for seed 42 on the common eligible test set. These describe agreement with teacher labels.}",
             "\\label{fig:pr}", "\\end{figure}"]
    write_tex(latex / "pr_plot.tex", "\n".join(plot))
    save_json(root / "pr_coordinates.json", curves)
    markdown = ["# Measured revision results", "",
                "Generated from the run JSONs by `src/build_artifacts.py`. All neural values use seeds 42, 43, and 44 on one grouped split.", "",
                "Targets are generated by a teacher. Scores do not measure independently verified misinformation.", "",
                f"Label cascade: {len(df):,} raw tweets; {df.eligible.sum():,} eligible; {df.accepted.sum():,} accepted. "
                f"Binary prompt agreement: {100 * quality['prompt_binary_agreement']:.1f}%.", "",
                "| Configuration | Binary macro-F1 (mean ± SD) | Author macro-F1 | Parameters | Binary train labels |",
                "|---|---:|---:|---:|---:|"]
    for name in order:
        s = summary[name]
        author = "not trained" if name == "SAGE-single-task" else f"{s['author_macro_f1']['mean']:.3f}"
        markdown.append(f"| {name} | {s['label_macro_f1']['mean']:.3f} ± {s['label_macro_f1']['sample_std']:.3f} "
                        f"| {author} | {s['parameters']:,} | {s['training_labels']:,} |")
    markdown += ["", "Text/majority baselines:", "",
                 "| Model | Binary macro-F1 | Positive precision | Positive recall |",
                 "|---|---:|---:|---:|"]
    for name, value in baselines.items():
        m = value["label"]
        markdown.append(f"| {name} | {m['macro_f1']:.3f} | {m['positive_precision']:.3f} | {m['positive_recall']:.3f} |")
    markdown += ["", "Paired bootstrap differences (deep GraphSAGE minus comparison):", "",
                 "| Comparison | Mean F1 difference | Conditional 95% interval |",
                 "|---|---:|---:|"]
    for c in comparisons:
        markdown.append(f"| {c['model_b']} | {c['mean_delta']:+.4f} | [{c['ci95'][0]:+.4f}, {c['ci95'][1]:+.4f}] |")
    markdown += ["", "Full-graph CPU timing (four threads, seven warm measurements; median):", "",
                 "| Model | Train step (ms) | Inference (ms) | Train IQR (ms) |",
                 "|---|---:|---:|---:|"]
    for row in scaling:
        if row["fraction"] == 1:
            markdown.append(f"| {row['model']} | {1000*row['train_median_seconds']:.0f} "
                            f"| {1000*row['inference_median_seconds']:.0f} | {1000*row['train_iqr_seconds']:.0f} |")
    markdown += ["", "These intervals are conditional on the generated targets and fixed split. "
                 "Historical September scores use another target/split and are not a controlled comparison."]
    markdown += ["", "Teacher throughput (24 fixed tweets, one prompt view, three NLI pairs/tweet; three repetitions):", "",
                 "| NLI pair batch size | Median seconds | Tweets per second |",
                 "|---|---:|---:|"]
    for row in teacher_timing["rows"]:
        markdown.append(f"| {row['pair_batch_size']} | {row['median_seconds']:.2f} | {row['tweets_per_second']:.2f} |")
    (root / "RESULTS.md").write_text("\n".join(markdown) + "\n", encoding="utf-8")
    print(json.dumps({"macros": macros, "comparisons": comparisons}, indent=2), flush=True)


if __name__ == "__main__":
    main()
